import { StyleSheet } from 'react-native';

import { MangAfriq } from '@/constants/theme';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: MangAfriq.bgLight,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: MangAfriq.textDark,
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: MangAfriq.textMuted,
    fontWeight: '500',
  },
  filterToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: MangAfriq.border,
    backgroundColor: MangAfriq.bgWhite,
  },
  filterToggleActive: {
    borderColor: MangAfriq.primary,
    backgroundColor: 'rgba(230, 57, 70, 0.04)',
  },
  filterToggleText: {
    fontSize: 14,
    fontWeight: '700',
    color: MangAfriq.textSecondary,
  },
  filterToggleTextActive: {
    color: MangAfriq.primary,
  },
  searchWrap: {
    position: 'relative',
    marginBottom: 14,
  },
  searchIcon: {
    position: 'absolute',
    left: 14,
    top: 13,
    zIndex: 1,
  },
  searchInput: {
    paddingLeft: 40,
    paddingRight: 40,
    paddingVertical: 11,
    fontSize: 15,
    color: MangAfriq.textDark,
    backgroundColor: MangAfriq.bgWhite,
    borderWidth: 1.5,
    borderColor: MangAfriq.border,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  searchClear: {
    position: 'absolute',
    right: 10,
    top: 10,
    padding: 4,
  },
  sortScroll: {
    marginBottom: 0,
  },
  sortScrollContent: {
    flexDirection: 'row',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 4,
    backgroundColor: MangAfriq.bgWhite,
    borderRadius: 6,
    alignSelf: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  sortBtn: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 5,
  },
  sortBtnActive: {
    backgroundColor: MangAfriq.primary,
  },
  sortBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: MangAfriq.textMuted,
  },
  sortBtnTextActive: {
    color: '#fff',
  },
  filtersPanel: {
    backgroundColor: MangAfriq.bgWhite,
    borderRadius: 10,
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  filterLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: MangAfriq.textDark,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  filterLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  clearGenres: {
    fontSize: 12,
    fontWeight: '600',
    color: MangAfriq.primary,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: MangAfriq.border,
    backgroundColor: MangAfriq.bgLight,
  },
  chipActive: {
    backgroundColor: MangAfriq.primary,
    borderColor: MangAfriq.primary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: MangAfriq.textSecondary,
  },
  chipTextActive: {
    color: '#fff',
  },
  activeFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  activeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(230, 57, 70, 0.2)',
    backgroundColor: 'rgba(230, 57, 70, 0.08)',
  },
  activeChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: MangAfriq.primary,
  },
  gridRow: {
    gap: 12,
    marginBottom: 12,
  },
  skeletonCard: {
    flex: 1,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: MangAfriq.bgWhite,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  skeletonThumb: {
    aspectRatio: 2 / 3,
    backgroundColor: '#ebebeb',
  },
  skeletonLine: {
    height: 14,
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 4,
    backgroundColor: '#ebebeb',
  },
  skeletonLineShort: {
    height: 12,
    width: '55%',
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 4,
    backgroundColor: '#ebebeb',
  },
  empty: {
    alignItems: 'center',
    paddingVertical: 64,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: MangAfriq.textDark,
    marginTop: 12,
    marginBottom: 6,
  },
  emptySub: {
    fontSize: 15,
    color: MangAfriq.textMuted,
    textAlign: 'center',
    marginBottom: 16,
  },
  emptyBtn: {
    backgroundColor: MangAfriq.primary,
    paddingVertical: 11,
    paddingHorizontal: 22,
    borderRadius: 6,
  },
  emptyBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  listPad: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  headerPad: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
});
