import { StyleSheet } from 'react-native';

import { MangAfriq } from '@/constants/theme';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: MangAfriq.bgLight,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  hero: {
    minHeight: 420,
    marginBottom: 8,
  },
  heroBg: {
    ...StyleSheet.absoluteFillObject,
  },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  heroBottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 200,
    backgroundColor: 'transparent',
  },
  heroInner: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 100,
  },
  heroBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  heroGenreTag: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    overflow: 'hidden',
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fff',
    lineHeight: 30,
    marginBottom: 8,
  },
  heroMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  heroMetaText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
  },
  heroSynopsis: {
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(255,255,255,0.9)',
    marginBottom: 16,
  },
  heroButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroBtnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: MangAfriq.primary,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  heroBtnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  heroBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  heroCoverWrap: {
    position: 'absolute',
    right: 8,
    bottom: 88,
    width: 120,
    height: 180,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  heroCover: {
    width: '100%',
    height: '100%',
  },
  heroControls: {
    position: 'absolute',
    bottom: 52,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  heroArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroDots: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  heroDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  heroDotActive: {
    backgroundColor: '#fff',
    width: 18,
  },
  genresSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  genresScroll: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 4,
  },
  genreChip: {
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: MangAfriq.border,
    backgroundColor: MangAfriq.bgWhite,
  },
  genreChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: MangAfriq.textSecondary,
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionBar: {
    width: 4,
    height: 20,
    borderRadius: 2,
    backgroundColor: MangAfriq.primary,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: MangAfriq.textDark,
  },
  seeAll: {
    fontSize: 13,
    fontWeight: '600',
    color: MangAfriq.primary,
    borderWidth: 1.5,
    borderColor: MangAfriq.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    overflow: 'hidden',
  },
  gridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  gridCell: {
    width: '50%',
    paddingHorizontal: 6,
    marginBottom: 12,
  },
  sidebarBlock: {
    backgroundColor: MangAfriq.bgWhite,
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: MangAfriq.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: MangAfriq.border,
  },
  sidebarTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: MangAfriq.textDark,
  },
  rankedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: MangAfriq.bgLight,
  },
  rankBadge: {
    width: 22,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '800',
    color: MangAfriq.textMuted,
  },
  rankTop1: { color: '#d4af37' },
  rankTop2: { color: '#a8a8a8' },
  rankTop3: { color: '#cd7f32' },
  rankedCover: {
    width: 40,
    height: 56,
    borderRadius: 5,
    backgroundColor: '#e0e0e0',
  },
  rankedInfo: {
    flex: 1,
    minWidth: 0,
  },
  rankedTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: MangAfriq.textDark,
  },
  rankedMeta: {
    fontSize: 11,
    color: MangAfriq.textMuted,
    marginTop: 2,
  },
  rankedStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  newRow: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: MangAfriq.bgLight,
  },
  newCover: {
    width: 48,
    height: 68,
    borderRadius: 6,
    backgroundColor: '#e0e0e0',
  },
  newInfo: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  newTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: MangAfriq.textDark,
  },
  newGenres: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  newGenrePill: {
    fontSize: 10,
    fontWeight: '600',
    color: MangAfriq.primary,
    backgroundColor: 'rgba(230, 57, 70, 0.08)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  newChapters: {
    fontSize: 11,
    color: MangAfriq.textMuted,
    marginTop: 4,
  },
  skeletonHero: {
    height: 400,
    backgroundColor: '#1a1a1a',
    marginBottom: 8,
    borderRadius: 0,
  },
});
